# Generated by Django 5.1.2 on 2024-10-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '__first__'),
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('filters', models.JSONField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
            options={
                'verbose_name': 'Чарт',
                'verbose_name_plural': 'Чарты',
                'db_table': 'charts',
                'managed': True,
            },
        ),
    ]
