# Generated by Django 5.1.2 on 2024-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chart',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
