# Generated by Django 5.0 on 2024-10-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('filters', models.JSONField()),
            ],
            options={
                'db_table': 'charts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('separator', models.CharField(max_length=5)),
                ('has_header', models.BooleanField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Пользователь', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chart')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dashboard')),
            ],
            options={
                'db_table': 'dashboards_charts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.BooleanField()),
                ('language', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'user_settings',
                'managed': True,
            },
        ),
    ]
