# Generated by Django 5.1.2 on 2024-10-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.BooleanField()),
                ('language', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
                'db_table': 'user_settings',
                'managed': True,
            },
        ),
    ]
