# Generated by Django 5.1.2 on 2024-10-21 13:47

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=files.models.get_file_path),
        ),
    ]
