# Generated by Django 5.1.2 on 2024-10-21 15:57

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.FileField(upload_to=files.models.get_file_path)),
                ('separator', models.CharField(max_length=5)),
                ('has_header', models.BooleanField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Встроенный файл',
                'verbose_name_plural': 'Встроенные файлы',
                'db_table': 'default_files',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
