# Generated by Django 5.1.2 on 2024-12-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_is_public_alter_file_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultFile',
        ),
    ]
