# Generated by Django 5.1.2 on 2024-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_delete_defaultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='files/'),
        ),
    ]
