# Generated by Django 5.1.2 on 2024-12-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='../media/files'),
        ),
    ]
