# Generated by Django 5.1.2 on 2024-12-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
